import numpy as np

fix_init = False
mineig = 1.0e-15
dorho = True
rho0 = 1.5
minlog = -1500  # XXX: -np.inf ?
epsdble = 1.0e-16
maxrej = 3
rejstart = 2
rejint = 3
doscaling = True
share_comps = False
share_start = 100
share_iter = 100
minrho = 1.0
maxrho = 2.0
invsigmin = 0.0 # default is 0.001 but config file set it to 0.0
invsigmax = 100 # default is 1000.0 but config file set it to 100
use_min_dll = True
use_grad_norm = True
min_dll = 1.000000e-09
maxincs = 5  # Number of consecutive iterations where likelihood increases by less than tol/min_dll before exiting
maxdecs = 3 # XXX: Default is 5 but somehow it is 3. Need to figure out why.
outstep = 1
restartiter = 10
numrestarts = 0
maxrestarts = 3
minlrate = 1.000000e-08 # Program Default is 1.0e-12 but config uses 1.0e-08
min_nd = 1.0e-7 # tol
lratefact = 0.5
rholratefact = 0.5 # Default is 0.1 but test config uses 0.5
load_gm = False
load_A = False
load_mu = False
load_sbeta = False
load_beta = False
load_rho = False
load_c = False
load_alpha = False
do_opt_block = False
do_approx_sphere = False

LOG_2 = np.log(2.0)
LOG_SQRT_PI = np.log(np.sqrt(np.pi))