# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  docs:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/amica-python
    steps:
      - checkout
      - run:
          name: Upgrade pip and tooling
          command: |
            python -m pip install --upgrade pip
            python -m pip --version
      - run:
          name: Install package with dev+doc extras
          command: |
            pip install -e ".[dev,doc]"
      - run:
          name: Build Sphinx docs
          command: |
            cd docs
            make html
      - persist_to_workspace:
          root: docs/build
          paths: html
      - store_artifacts:
          path: docs/build/html
          destination: docs_html
  
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Disable jekyll builds
          command: touch docs/build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "seh33@uw.edu"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ELRqw7gZgNGI2r8OMpiRI0pqyjSr1LGMZKVr998bNbQ"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Automatic commit from CircleCI" --dist docs/build/html

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  build-docs:
    jobs:
      - docs
      - docs-deploy:
          requires:
            - docs
          filters:
            branches:
              only: main
