# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  docs:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/amica-python
    steps:
      - checkout
      - run:
          name: Upgrade pip and tooling
          command: |
            python -m pip install --upgrade pip
            python -m pip --version
      - run:
          name: Install package with dev+doc extras
          command: |
            pip install -e ".[dev,doc]"
      - run:
          name: Build Sphinx docs
          command: |
            cd docs
            make html
      - store_artifacts:
          path: docs/_build/html
          destination: docs_html

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  build-docs:
    jobs:
      - docs
