name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Create cache directory if not exists
        run: mkdir -p /tmp/.uv-cache

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: | # fallback key
            uv-${{ runner.os }}-

      - name: Install package and check import
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          python -c "import amica"

      - name: Install dev extras
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest src/amica/tests/test_amica.py
      
      - name: Minimize uv cache
        run: uv cache prune --ci