name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/_setup.yml
        with:
          python-version: '3.11'
      - name: Install dev extras
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
      - name: Run ruff
        run: |
          source .venv/bin/activate
          ruff --check src/amica

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.10', '3.11']

    steps:
      - uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and check import
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          python -c "import amica"

      - name: Install dev extras
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest src/amica/tests/test_amica.py
      
      - name: Minimize uv cache
        run: uv cache prune --ci